# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Agiliq
email: hello@agiliq.com
description: >- # this means to ignore newlines until "baseurl:"
  Agiliq builds amazing apps using modern tools.
baseurl: "" # the subpath of your site, e.g. /blog. Don't keep the trailing /'
url: "https://agiliq.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: agiliqdotcom
github_username:  agiliq
show_excerpts: false
excerpt_separator: <!--more-->

permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Theme settings
doks:
    baseurl: ""
    color_theme: green
    header:
        logo:
            text: Agiliq
            image:
        nav:
            - item_name: Blog
              item_url: '/blog/'
            - item_name: About Us
              item_url: '/about/'
            - item_name: Contact
              item_url: '/contact/'
    footer:
        content:
            logo:
                text: Agiliq
                image:
            copyright: Copyright &copy; 2010-2018,  Agiliq <br>All rights reserved.
        social_list:
            - network_name: facebook
              profile_url: 'https://facebook.com/agiliq'
            - network_name: twitter
              profile_url: 'https://twitter.com/agiliqdotcom'
            - network_name: github
              profile_url: 'https://github.com/agiliq'
    google_analytics:
        tracking_code: "UA-367368-15"
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /blog/:year/:month/:day/:title/
